# Generated by Django 5.0 on 2026-01-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_remove_organization_terminal_group_and_more"),
        ("users", "0002_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terminals",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="organizations.terminal",
                verbose_name="Присвоенные терминалы",
            ),
        ),
    ]
