# Generated by Django 5.0 on 2026-01-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_remove_organization_terminal_group_and_more"),
        ("users", "0003_user_terminals"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="city_name",
            field=models.CharField(
                default="Не указан", max_length=100, verbose_name="Город"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="iiko_city_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID города iiko"
            ),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="iiko_street_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="ID улицы iiko"),
        ),
        migrations.AddField(
            model_name="deliveryaddress",
            name="street_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Улица"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="flat",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Квартира/Офис"
            ),
        ),
        migrations.AlterField(
            model_name="deliveryaddress",
            name="street",
            field=models.ForeignKey(
                blank=True,
                db_column="street_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="organizations.street",
                verbose_name="Улица (из справочника)",
            ),
        ),
    ]
