# Generated by Django 5.0 on 2026-01-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_city_terminal_city_alter_street_city"),
        ("users", "0004_deliveryaddress_city_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryaddress",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="addresses",
                to="organizations.city",
                verbose_name="Город (из справочника)",
            ),
        ),
    ]
