# Generated by Django 5.0 on 2026-01-27 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_deliveryaddress_city"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingPhone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Основной"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_phones",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Биллинг‑номер",
                "verbose_name_plural": "Биллинг‑номера",
                "db_table": "billing_phones",
                "indexes": [
                    models.Index(
                        fields=["user"], name="billing_pho_user_id_7ce61b_idx"
                    ),
                    models.Index(fields=["phone"], name="billing_pho_phone_8bd850_idx"),
                ],
            },
        ),
    ]
