# Generated by Django 4.2.27 on 2026-01-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_deliveryaddress_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_code',
            field=models.CharField(blank=True, default='kz', help_text='Предпочитаемый язык интерфейса: kz, ru', max_length=5, verbose_name='Код языка'),
        ),
    ]
