# Generated by Django 5.0 on 2026-03-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_add_bot_subscription_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="botsynctoken",
            index=models.Index(
                fields=["bot_sync_uuid"], name="bot_sync_to_bot_syn_151f68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="botsynctoken",
            index=models.Index(
                fields=["created_at"], name="bot_sync_to_created_27ea4c_idx"
            ),
        ),
    ]
