# Generated by Django 5.0 on 2026-05-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("organizations", "0024_organization_tma_name"),
        ("users", "0010_fix_unreflected_model_changes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Telegram ID"
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                fields=("telegram_id", "organization"),
                name="unique_telegram_user_per_org",
            ),
        ),
    ]
