# Generated by Django 5.0 on 2026-01-11 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("organizations", "0001_initial"),
        ("products", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.ForeignKey(
                blank=True,
                db_column="delivery_address_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="users.deliveryaddress",
                verbose_name="Адрес доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="organization",
            field=models.ForeignKey(
                db_column="org_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="organizations.organization",
                verbose_name="Организация",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.ForeignKey(
                blank=True,
                db_column="payment_type_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="organizations.paymenttype",
                verbose_name="Тип оплаты",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                db_column="order_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="orders.order",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                db_column="product_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="products.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AddField(
            model_name="orderitemmodifier",
            name="modifier",
            field=models.ForeignKey(
                db_column="modifier_id",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_usage",
                to="products.modifier",
                verbose_name="Модификатор",
            ),
        ),
        migrations.AddField(
            model_name="orderitemmodifier",
            name="order_item",
            field=models.ForeignKey(
                db_column="order_item_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifiers",
                to="orders.orderitem",
                verbose_name="Позиция заказа",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["user"], name="orders_user_id_4e08b8_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["organization"], name="orders_org_id_4495b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="orders_status_762191_idx"),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["created_at"], name="orders_created_77e2b9_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitem",
            index=models.Index(fields=["order"], name="order_items_order_i_26ad88_idx"),
        ),
        migrations.AddIndex(
            model_name="orderitemmodifier",
            index=models.Index(
                fields=["order_item"], name="order_item__order_i_15de8c_idx"
            ),
        ),
    ]
