# Generated by Django 5.0 on 2026-01-13 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
        ("organizations", "0003_remove_organization_terminal_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                db_column="terminal_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="organizations.terminal",
                verbose_name="Терминал",
            ),
        ),
    ]
