# Generated by Django 5.0 on 2026-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_terminal"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="correlation_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="Correlation ID iiko"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="iiko_delivery_number",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Номер доставки iiko",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("confirmed", "Подтвержден"),
                    ("preparing", "Готовится"),
                    ("delivering", "Доставляется"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменен"),
                    ("error", "Ошибка"),
                    ("InProgress", "В процессе iiko"),
                    ("Success", "Успешно создан в iiko"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
