# Generated by Django 5.0 on 2026-01-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_correlation_id_order_iiko_delivery_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="query_to_iiko",
            field=models.JSONField(blank=True, null=True, verbose_name="Запрос в iiko"),
        ),
    ]
