# Generated by Django 4.2.27 on 2026-01-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_query_to_iiko'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 — бесплатно', max_digits=10, verbose_name='Стоимость доставки'),
        ),
    ]
