# Generated by Django 5.0 on 2026-01-11 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "menu_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "menu_name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активно"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Меню",
                "verbose_name_plural": "Меню",
                "db_table": "menus",
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                ("subgroup_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "subgroup_name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="products.menu",
                        verbose_name="Меню",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория продуктов",
                "verbose_name_plural": "Категории продуктов",
                "db_table": "product_categories",
                "ordering": ["order_index", "subgroup_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "product_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Код"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "measure_unit",
                    models.CharField(
                        default="порция",
                        max_length=50,
                        verbose_name="Единица измерения",
                    ),
                ),
                (
                    "has_modifiers",
                    models.BooleanField(
                        default=False, verbose_name="Есть модификаторы"
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Доступен"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="URL изображения",
                    ),
                ),
                ("order_index", models.IntegerField(default=0, verbose_name="Порядок")),
                (
                    "updated_from_iiko",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обновлено из iiko"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.menu",
                        verbose_name="Меню",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="products.productcategory",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "db_table": "products",
                "ordering": ["order_index", "product_name"],
            },
        ),
        migrations.CreateModel(
            name="StopList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Название продукта"),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Остаток продукта на складе",
                        max_digits=10,
                        verbose_name="Остаток",
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, null=True, verbose_name="Причина"),
                ),
                (
                    "is_auto_added",
                    models.BooleanField(
                        default=True, verbose_name="Добавлен автоматически"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_list",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stop_list_entries",
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Стоп-лист",
                "verbose_name_plural": "Стоп-лист",
                "db_table": "stop_list",
            },
        ),
        migrations.CreateModel(
            name="Modifier",
            fields=[
                ("modifier_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "modifier_name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "min_amount",
                    models.IntegerField(
                        default=0, verbose_name="Минимальное количество"
                    ),
                ),
                (
                    "max_amount",
                    models.IntegerField(
                        default=1, verbose_name="Максимальное количество"
                    ),
                ),
                (
                    "modifier_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Код"
                    ),
                ),
                (
                    "modifier_weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="Обязательный"),
                ),
                (
                    "updated_from_iiko",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Обновлено из iiko"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="products.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модификатор",
                "verbose_name_plural": "Модификаторы",
                "db_table": "modifiers",
                "indexes": [
                    models.Index(
                        fields=["product"], name="modifiers_product_f96e28_idx"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["menu"], name="products_menu_id_141187_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["organization"], name="products_organiz_d068f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_available"], name="products_is_avai_39744e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stoplist",
            index=models.Index(fields=["product"], name="stop_list_product_075571_idx"),
        ),
        migrations.AddIndex(
            model_name="stoplist",
            index=models.Index(
                fields=["organization"], name="stop_list_organiz_a9d081_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stoplist",
            unique_together={("product", "organization")},
        ),
    ]
