# Generated by Django 5.0 on 2026-01-12 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="outer_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Данные из iiko"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parent_group",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Родительская группа (имя)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="Тип (Dish, Good, etc)",
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="outer_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Данные из iiko"
            ),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="products.productcategory",
                verbose_name="Родительская категория",
            ),
        ),
    ]
