# Generated by Django 5.0 on 2026-01-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_outer_data_product_parent_group_product_type_and_more"),
        ("organizations", "0009_terminal_stop_list_interval_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="stoplist",
            name="terminal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stop_list",
                to="organizations.terminal",
                verbose_name="Терминал",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stoplist",
            unique_together={("product", "terminal")},
        ),
        migrations.AddIndex(
            model_name="stoplist",
            index=models.Index(fields=["terminal"], name="stop_list_terminal_idx"),
        ),
    ]
