# Generated by Django 5.0 on 2026-01-27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_stoplist_terminal_unique_together"),
        ("organizations", "0012_terminal_working_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="FastMenuGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название группы")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок сортировки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создана")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлена")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fast_menu_groups",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Группа быстрого меню",
                "verbose_name_plural": "Группы быстрого меню",
                "db_table": "fast_menu_groups",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="FastMenuItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлен")),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.fastmenugroup",
                        verbose_name="Группа",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fast_menu_items",
                        to="products.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Элемент быстрого меню",
                "verbose_name_plural": "Элементы быстрого меню",
                "db_table": "fast_menu_items",
                "ordering": ["order", "product__product_name"],
            },
        ),
        migrations.AddIndex(
            model_name="fastmenugroup",
            index=models.Index(fields=["organization"], name="fast_menu_g_organiz_idx"),
        ),
        migrations.AddIndex(
            model_name="fastmenugroup",
            index=models.Index(fields=["is_active"], name="fast_menu_g_is_acti_idx"),
        ),
        migrations.AddIndex(
            model_name="fastmenugroup",
            index=models.Index(fields=["order"], name="fast_menu_g_order_idx"),
        ),
        migrations.AddIndex(
            model_name="fastmenuitem",
            index=models.Index(fields=["group"], name="fast_menu_i_group_idx"),
        ),
        migrations.AddIndex(
            model_name="fastmenuitem",
            index=models.Index(fields=["product"], name="fast_menu_i_product_idx"),
        ),
        migrations.AddIndex(
            model_name="fastmenuitem",
            index=models.Index(fields=["order"], name="fast_menu_i_order_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="fastmenuitem",
            unique_together={("group", "product")},
        ),
    ]
