# Generated by Django 4.2.27 on 2026-02-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_fastmenugroup_fastmenuitem'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fastmenugroup',
            new_name='fast_menu_g_organiz_56a80c_idx',
            old_name='fast_menu_g_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='fastmenugroup',
            new_name='fast_menu_g_is_acti_0649e2_idx',
            old_name='fast_menu_g_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='fastmenugroup',
            new_name='fast_menu_g_order_66417c_idx',
            old_name='fast_menu_g_order_idx',
        ),
        migrations.RenameIndex(
            model_name='fastmenuitem',
            new_name='fast_menu_i_group_i_55bbe3_idx',
            old_name='fast_menu_i_group_idx',
        ),
        migrations.RenameIndex(
            model_name='fastmenuitem',
            new_name='fast_menu_i_product_4226e0_idx',
            old_name='fast_menu_i_product_idx',
        ),
        migrations.RenameIndex(
            model_name='fastmenuitem',
            new_name='fast_menu_i_order_fd7e69_idx',
            old_name='fast_menu_i_order_idx',
        ),
        migrations.RenameIndex(
            model_name='stoplist',
            new_name='stop_list_termina_073d69_idx',
            old_name='stop_list_terminal_idx',
        ),
        migrations.AddField(
            model_name='menu',
            name='source_type',
            field=models.CharField(choices=[('nomenclature', 'Номенклатура'), ('external', 'Внешнее')], default='nomenclature', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активно'),
        ),
    ]
