# Generated by Django 4.2 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_menu_is_active_default_and_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Метаданные'),
        ),
    ]
