# Generated by Django 5.0 on 2026-01-11 19:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Terminal",
            fields=[
                ("terminal_id", models.UUIDField(primary_key=True, serialize=False)),
                ("terminal_group_id", models.UUIDField(unique=True)),
                (
                    "terminal_group_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Название терминала",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
            ],
            options={
                "verbose_name": "Терминал",
                "verbose_name_plural": "Терминалы",
                "db_table": "terminals",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "org_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("org_name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="API Key iiko",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "terminal_group",
                    models.ForeignKey(
                        blank=True,
                        db_column="terminal_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="organizations",
                        to="organizations.terminal",
                        verbose_name="Терминал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
                "db_table": "organizations",
            },
        ),
        migrations.CreateModel(
            name="PaymentType",
            fields=[
                ("payment_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "payment_name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "payment_type",
                    models.CharField(max_length=100, verbose_name="Тип оплаты (код)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_types",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип оплаты",
                "verbose_name_plural": "Типы оплаты",
                "db_table": "payment_types",
                "unique_together": {("organization", "payment_id")},
            },
        ),
        migrations.CreateModel(
            name="Street",
            fields=[
                ("street_id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "street_name",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                (
                    "iiko_street_id",
                    models.UUIDField(blank=True, null=True, verbose_name="ID в iiko"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="Удалена"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streets",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Улица",
                "verbose_name_plural": "Улицы",
                "db_table": "streets",
                "indexes": [
                    models.Index(
                        fields=["organization"], name="streets_organiz_30b9b4_idx"
                    ),
                    models.Index(
                        fields=["street_name"], name="streets_street__39922a_idx"
                    ),
                ],
            },
        ),
    ]
