# Generated by Django 5.0 on 2026-01-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="iiko_organization_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID организации в iiko",
            ),
        ),
    ]
