# Generated by Django 5.0 on 2026-01-13 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_organization_iiko_organization_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="terminal_group",
        ),
        migrations.AddField(
            model_name="organization",
            name="terminals",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizations",
                to="organizations.terminal",
                verbose_name="Терминалы",
            ),
        ),
    ]
