# Generated by Django 5.0 on 2026-01-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_remove_organization_terminal_group_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="terminals",
        ),
        migrations.RemoveField(
            model_name="terminal",
            name="terminal_group_id",
        ),
        migrations.AddField(
            model_name="terminal",
            name="iiko_organization_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID организации в iiko",
            ),
        ),
        migrations.AddField(
            model_name="terminal",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="terminals",
                to="organizations.organization",
                verbose_name="Организация",
            ),
        ),
    ]
