# Generated by Django 5.0 on 2026-01-13 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_remove_organization_terminals_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                ("city_id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cities",
                        to="organizations.organization",
                        verbose_name="Организация",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
                "db_table": "cities",
                "unique_together": {("organization", "city_id")},
            },
        ),
        migrations.AddField(
            model_name="terminal",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminals",
                to="organizations.city",
                verbose_name="Город",
            ),
        ),
        migrations.AlterField(
            model_name="street",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="streets",
                to="organizations.city",
                verbose_name="Город",
            ),
        ),
    ]
