# Generated by Django 5.0 on 2026-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0005_city_terminal_city_alter_street_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="iiko_city_id",
            field=models.UUIDField(blank=True, null=True, verbose_name="ID в iiko"),
        ),
    ]
