# Generated by Django 5.0 on 2026-01-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_city_iiko_city_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="address",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Адрес"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="phone",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Телефон"
            ),
        ),
    ]
