# Generated by Django 5.0 on 2026-01-24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_organization_address_organization_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="bot_token",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Токен Telegram бота",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="bot_username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Юзернейм Telegram бота",
            ),
        ),
    ]
