# Generated by Django 5.0 on 2026-01-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_organization_bot_token_organization_bot_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="terminal",
            name="stop_list_interval_min",
            field=models.IntegerField(
                default=30,
                help_text="Частота обновления стоп-листа в минутах",
                verbose_name="Интервал обновления стоп-листа (мин)",
            ),
        ),
    ]
