# Generated by Django 5.0 on 2026-01-27 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0012_terminal_working_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttype",
            name="system_type",
            field=models.CharField(
                blank=True,
                help_text="Варианты: cash, remote_payment, card_on_delivery и др.",
                max_length=50,
                null=True,
                verbose_name="Системный тип",
            ),
        ),
        migrations.AlterField(
            model_name="paymenttype",
            name="payment_id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
