# Generated by Django 4.2.27 on 2026-01-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_terminal_is_delivery_calculation_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='instagram_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на Instagram'),
        ),
    ]
