# Generated by Django 5.0 on 2026-03-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0018_add_discount_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="yandex_maps_api_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="API-ключ Яндекс.Карт (Геокодер)",
            ),
        ),
    ]
