# Generated by Django 5.0 on 2026-03-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0022_organization_webhook_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="api_custom_params",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Доступные блоки для масштабирования: order, customer, createOrderSettings, address. Пример: {"order": {"comment": "Срочно"}, "createOrderSettings": {"servicePrint": true}}',
                null=True,
                verbose_name="Дополнительные параметры (Редактируемый)",
            ),
        ),
    ]
