# Generated by Django 4.2.27 on 2026-05-14 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_fix_unreflected_model_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tma_name',
            field=models.CharField(blank=True, help_text='Например, "app"', max_length=255, null=True, verbose_name='Shortname Telegram Mini App (TMA)'),
        ),
    ]
